### ISSUE TITLE
AWS-SDK Version 1 Calls

### ISSUE THREAD

**Issue by jerryk55** [ManageIQ/amazon_ssa_support#19]
There is at least one cases of an AWS-SDK version 1 call still in the code.  
SsaQueue.get_reply calls read on an S3 Object, which is outdated.

@hsong-rh @roliveri FYI.

**Comment by jerryk55** [comment]
@miq-bot assign_issue @hsong-rh

**Comment by jerryk55** [comment]
@miq-bot assign @hsong-rh

**Comment by hsong-rh** [comment]
Fixed. Closed issue.
